---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: kagent-system
    app.kubernetes.io/part-of: kagent
  name: kagent
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  labels:
    app.kubernetes.io/instance: kagent-system
    app.kubernetes.io/part-of: kagent
  name: kagent
  namespace: kagent
spec:
  interval: 1m0s
  type: "oci"
  url: oci://ghcr.io/kagent-dev/kagent/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    app.kubernetes.io/instance: kagent-system
    app.kubernetes.io/part-of: kagent
  name: kagent-crds
  namespace: kagent
spec:
  interval: 1m0s
  chart:
    spec:
      interval: 1m0s
      chart: kagent-crds
      sourceRef:
        kind: HelmRepository
        name: kagent
  releaseName: kagent-crds
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    app.kubernetes.io/instance: kagent-system
    app.kubernetes.io/part-of: kagent
  name: kagent
  namespace: kagent
spec:
  interval: 1m0s
  dependsOn:
    - name: kagent-crds
  chart:
    spec:
      interval: 1m0s
      chart: kagent
      sourceRef:
        kind: HelmRepository
        name: kagent
  releaseName: kagent
  values:
    agents:
      k8s-agent:
        enabled: false
      kgateway-agent:
        enabled: false
      istio-agent:
        enabled: false
      promql-agent:
        enabled: false
      observability-agent:
        enabled: false
      argo-rollouts-agent:
        enabled: false
      helm-agent:
        enabled: false
      cilium-policy-agent:
        enabled: false
      cilium-manager-agent:
        enabled: false
      cilium-debug-agent:
        enabled: false
    tools:
      grafana-mcp:
        enabled: false
      querydoc:
        enabled: false
---
apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  labels:
    app.kubernetes.io/instance: kagent-system
    app.kubernetes.io/part-of: kagent
  name: vercel-config
  namespace: kagent
spec:
  apiKeySecret: vercel-provider
  apiKeySecretKey: VERCEL_API_KEY
  model: "openai/gpt-5.1-thinking"
  provider: OpenAI
  openAI:
    baseUrl: "https://ai-gateway.vercel.sh/v1"
---
apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  labels:
    app.kubernetes.io/instance: kagent-system
    app.kubernetes.io/part-of: kagent
  name: chatbot
  namespace: kagent
spec:
  declarative:
    modelConfig: vercel-config
    stream: true
    systemMessage: |-
      You're a helpful agent, made by the kagent team.

      # Instructions
          - If user question is unclear, ask for clarification before running any tools
          - Always be helpful and friendly
          - If you don't know how to answer the question DO NOT make things up, tell the user "Sorry, I don't know how to answer that" and ask them to clarify the question further
          - If you are unable to help, or something goes wrong, refer the user to https://kagent.dev for more information or support.

      # Response format:
          - ALWAYS format your response as Markdown
          - Your response will include a summary of actions you took and an explanation of the result
          - If you created any artifacts such as files or resources, you will include those in your response as well
  description: Chatbot
  type: Declarative
