---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: kagent-system
    app.kubernetes.io/part-of: kagent
  name: kagent
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  labels:
    app.kubernetes.io/instance: kagent-system
    app.kubernetes.io/part-of: kagent
  name: kagent
  namespace: kagent
spec:
  interval: 1m0s
  type: "oci"
  url: oci://ghcr.io/kagent-dev/kagent/helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    app.kubernetes.io/instance: kagent-system
    app.kubernetes.io/part-of: kagent
  name: kagent-crds
  namespace: kagent
spec:
  interval: 1m0s
  chart:
    spec:
      interval: 1m0s
      chart: kagent-crds
      sourceRef:
        kind: HelmRepository
        name: kagent
  releaseName: kagent-crds
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  labels:
    app.kubernetes.io/instance: kagent-system
    app.kubernetes.io/part-of: kagent
  name: kagent
  namespace: kagent
spec:
  interval: 1m0s
  dependsOn:
    - name: kagent-crds
  chart:
    spec:
      interval: 1m0s
      chart: kagent
      sourceRef:
        kind: HelmRepository
        name: kagent
  releaseName: kagent
  values:
    agents:
      k8s-agent:
        enabled: false
      kgateway-agent:
        enabled: false
      istio-agent:
        enabled: false
      promql-agent:
        enabled: false
      observability-agent:
        enabled: false
      argo-rollouts-agent:
        enabled: false
      helm-agent:
        enabled: false
      cilium-policy-agent:
        enabled: false
      cilium-manager-agent:
        enabled: false
      cilium-debug-agent:
        enabled: false
    tools:
      grafana-mcp:
        enabled: false
      querydoc:
        enabled: false
---
apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: vercel-config
  namespace: kagent
spec:
  apiKeySecret: vercel-provider
  apiKeySecretKey: VERCEL_API_KEY
  model: "openai/gpt-5"
  provider: OpenAI
  openAI:
    baseUrl: "https://ai-gateway.vercel.sh/v1"
